### ISSUE TITLE
Training on the ETH dataset.

### ISSUE THREAD

**Issue by huang-xx** [huang-xx/STGAT#1]
For the case where the prediction length is 8 time-steps, the result in the paper will appear at the 256th epoch.  No need to change parameters.

For the case where the prediction length is 12 time-steps, do the following things:
1. Change "lr" to `1e-5` in line 148 and 149 in train.py;  
2. Change value  `150` to `30` in line 173 in train.py;
3. Comment out the 175th and 176th line of code in train.py
4. Change value `250` to `30` in line 178 in train.py.
5. Change value `5e-3`  to `1e-4` in line 180 in train.py.
6. Set the 'seed' to `86` in line 20 in evaluate_model.py.

You will get the result at epoch 54.

**Comment by JiyouSeo** [comment]
@huang-xx Should I set the seed to ```86``` when I run the code ```train.py```?
