### ISSUE TITLE
running the code and pretrained model

### ISSUE THREAD

**Issue by golnazhabibi3** [huang-xx/STGAT#10]
Hi, thanks for the great work. I  have just started running the code and wondering if there is a pretrained model so I can just run the evaluation. Also, when I run train.py I have got the error :    File "train.py", line 196
    f"./checkpoint/checkpoint{epoch}.pth.tar",
                                            ^
SyntaxError: invalid syntax

Should I set any parameter or argument before running train.py?

Thanks!

**Comment by huang-xx** [comment]
@golnazhabibi3   I think the Python version causes the error. Please make sure your Python version is higher than 3.6 (the f-string is introduced in version 3.6). And the pre-trained model may be uploaded later (after I return to my lab).
