### ISSUE TITLE
Question about short test trajectories

### ISSUE THREAD

**Issue by golnazhabibi3** [huang-xx/STGAT#11]
Hi, my question is about trajectories with less than 20 frames (so we cannot observe 8 frames and predict 12 frames since the test trajectory should  have 20 frames at least.). I observe all test dataset more or less contain these trajectories. How did you run evaluation on theses short trajectories? Did you remove them or adjust the time horizon for theses trajectories?

**Comment by huang-xx** [comment]
@golnazhabibi3  When I wrote the code of my method, most existing methods only focused on the pedestrians who are involved in the scene all the time from T_{obs} to T_{pred}. This data processing operation can be checked in the publicly available code segment of [SGAN](https://github.com/agrimgupta92/sgan/blob/a83b538deacca862ae83fdfd85782de01f475e01/sgan/data/trajectories.py#L131)  and [CIDNN](https://github.com/svip-lab/CIDNN/blob/1574d071a9eac3be65615e1eaa49f760eadc2dcb/tools/create_dataset.py#L66).  We also follow this policy to process trajectories.
