### ISSUE TITLE
Initializing Training and Validation sets takes too long on own Dataset

### ISSUE THREAD

**Issue by ahariri13** [huang-xx/STGAT#2]
Hi ! I am trying to implement this data on a data of my own for trajectory prediction. I have used the format: *frame id- person id - x -y*  as well. 

It's taking around 24 hours to initialize the training dataset of around 5000 samples of 40 frames each. I understand that it would normally take longer since my data is considerably bigger, but is there a way I can speed up the initialization process ? It takes more than a whole day for me to obtain the FDE and ADE results. Should I try transforming the data to numpy arrays or pandas dataframes?

**Comment by huang-xx** [comment]
@ahariri13 Yes, you should save the pre-processed data (the data that can be read directly by Pytorch Dataloader) to the hard drive (in some form like .npz or .pkl), then you can just read it directly in your following work.  Check this [link](https://github.com/svip-lab/CIDNN/blob/master/tools/create_dataset.py), it may give you some help.
