### ISSUE TITLE
training_step in train.py and models.py

### ISSUE THREAD

**Issue by saruvora** [huang-xx/STGAT#4]
Hi thank you for uploading the algorithm along with the paper. I have just started working on it. I noticed that when training_step = 1 you read the output from traj_lstm and for 2 and 3 you have different approaches can you please explain about it ? as in what exactly you intend to do there ? because it keeps on changing per the number of epochs. 

Thank you

**Comment by huang-xx** [comment]
@saruvora  To speed up the training of the model, the network is trained in three stages, and each stage contains one type of LSTM. The first part of the model ('traj_lstm') is trained in 'Step1'. After 'Step1' has converged, another LSTM model ('graph_lstm') joined the training process in 'Step2'. 'Step1' and 'Step2' have the same input data and ground-truth output data. After that, the whole model is jointly trained.

**Comment by ry85** [comment]
What if we don't have steps 1 and 2, and just have step 3 only. In this scenario also can we expect to get the same results (in case if you have tried this too).
