### ISSUE TITLE
reproduce the ADE/FDE for eth and zara1

### ISSUE THREAD

**Issue by howiechasefuture** [huang-xx/STGAT#7]
Hi,

Thank you for providing the code. 
I am trying to train the models for eth and zara1 with prediction length as 12, but I can't achieve (ade/fde) reported in the paper. (eth: 0.65/1.12 and zara1: 0.34/0.69.)
Can you share the parameters for these two datasets? 
Thank you.

**Comment by huang-xx** [comment]
@howiechasefuture  For the ETH dataset, please check this [issue](https://github.com/huang-xx/STGAT/issues/1). In my memory, for other datasets, the default parameters in the code should produce results very close to those in the paper. I can't access my lab computer right now, and I may upload the pre-trained model later.

**Comment by JiyouSeo** [comment]
@huang-xx hello, can you let me know about hyper parameter of UCY(univ, zara1, zara2) dataset  too?
Thank you !
