### ISSUE TITLE
issue on  evaluate.py 

### ISSUE THREAD

**Issue by learning-sketch** [huang-xx/STGAT#8]
Hi, thank u for sharing your code. I have trained the  model.but  i can't run  the  evaluate.py. I meet this 
error :  cublas runtime error : library not initialized at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCGeneral.cpp:228.  Can you help me? Thank you.

**Comment by huang-xx** [comment]
@1earninging You may need to create a new Conda environment and re-install Pytorch. And make sure everything related to Cuda works well.
