### ISSUE TITLE
Can't find an embbeding layer of trajectory input.

### ISSUE THREAD

**Issue by sanmin0312** [huang-xx/STGAT#9]
Hello, thank you for sharing your code. I have two questions.
I just found that the input size of traj_lstm (M-LSTM in the paper) is 2, which means there is no embedding, and also can't find the embedding layer in your code. Can you explain it?

**Comment by huang-xx** [comment]
@sanmin0312 When I clean up the code before release, I find the embedding layer doesn't have much significant influence on the result. So the embedding layer has been removed.

**Comment by sanmin0312** [comment]
Ok. Thank you for your answer :)
